spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/netdisc?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  type-aliases-package: com.chenle.netdisc.pojo
  mapper-locations: classpath:mybatis/*.xml
